# A short, descriptive name of this building block collection
name: Land parcels

# Short abstract for this collection (optional)
abstract: |
  This repository contains building blocks for land parcels.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.land-parcels.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
