"$schema": https://json-schema.org/draft/2020-12/schema
type: object
allOf:
  - anyOf:
    # a set of parcels can be a set of topo features with polygons defined topologically by reference
      - $ref: bblocks://ogc.geo.topo.features.topo-feature-collection
    # Or simply features with geometry
      - $ref: bblocks://ogc.geo.json-fg.featureCollection-lenient
  - properties:
      spatialRepresentationDefinitions:
        $ref: bblocks://ogc.ladm.land-parcels.parcelSpatialRepresentationDefinition
      features:
        items:
          $ref: bblocks://ogc.ladm.land-parcels.parcel
